module.exports = {
  HOURS: 'hours',
  MINUTES: 'minutes',
  SECONDS: 'seconds',
  DAYS: 'days',
  PERCENTAGE: 'percentage',
  CELSIUS: 'celsius',
  FAHRENHEIT: 'fahrenheit',
  RPM: 'rpm',
  KELVIN: 'kelvin',
  WATT: 'watt',
  VOLT: 'volt',
  AMPERE: 'ampere',
  LUX: 'lux',
  PPM: 'ppm',
  RGB: 'rgb',
  UGM3: 'μg/m3',
  MGM3: 'mg/m3',
  ARCDEGREE: 'arcdegree',
  MEGABYTE: 'megabyte',
  NONE: 'none'
};
