module.exports = {
  POWER: 'power',
  MODE: 'mode',
  CHILD_LOCK: 'child_lock',
  ALARM: 'alarm',
  LED: 'led',
  SCREEN_BRIGHTNESS: 'screen_brightness',
  POWER_OFF_TIME: 'power_off_time',
  BRIGHTNESS: 'brightness',
  COLOR_TEMP: 'color_temp',
  FLOW: 'flow',
  FAN_SPEED: 'fan_speed',
  FAN_SPEED_RPM: 'fan_speed_rpm',
  FAN_LEVEL: 'fan_level',
  BATTERY_POWER: 'battery_power',
  AC_POWER: 'ac_power',
  BATTERY_LEVEL: 'battery_level',
  RELATIVE_HUMIDITY: 'relative_humidity',
  TEMPERATURE: 'temperature',
  USE_TIME: 'use_time',
  STATUS: 'status',
  DEVICE_FAULT: 'device_fault',
  COUNTRY_CODE: 'country_code'
};
